version: '3.8'

networks:
  general_general:
    external: true

volumes:
  ad-guard-work:
  ad-guard-conf:

services:
  ad-guard:
    container_name: ad-guard
    image: adguard/adguardhome:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "853:853/udp"
    expose:
      - "80/tcp"
      - "80/udp"
      - "443/tcp"
      - "443/udp"
      - "3000"
    volumes:
      - ad-guard-work:/opt/adguardhome/work
      - ad-guard-conf:/opt/adguardhome/conf
      - ${CERTS_PATH}/fullchain.pem:/certs/cert.pem:ro
      - ${CERTS_PATH}/privkey.pem:/certs/key.pem:ro
    networks:
      general_general:
        ipv4_address: 172.23.0.253