networks:
  keycloak:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    command: start --hostname=${HOSTNAME}
    environment:
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KEYCLOAK_ADMIN: ${KC_USER}
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: pg-prd
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${PG_USER}
      KC_DB_PASSWORD: ${PG_PASS}

      KC_PROXY_HEADERS: xforwarded
    expose:
      - "8080"
    networks:
      keycloak: