name: pg

networks:
  general:
    external: true

services:
  pg:
    container_name: pg
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - ~/pg:/var/lib/postgresql
    networks:
      - general