networks:
  general_general:
    external: true

services:
  pg:
    container_name: pg
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - /pg/prd:/var/lib/postgresql/data
    networks:
      general_general: