networks:
  general:
    ipam:
      config:
        - subnet: "172.23.0.0/24"

volumes:
  portainer:

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    expose:
      - 9443
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - general