version: '3.8'

volumes:
  redis-dev:
  redis-prd:

services:
  redis-dev:
    container_name: redis-dev
    image: redis:alpine
    restart: always
    command: 'redis-server --requirepass ${DEV_REDIS_PASS}'
    volumes:
      - redis-dev:/data
    ports:
      - "6378:6379"
  redis-prd:
    container_name: redis-prd
    image: redis:alpine
    restart: always
    command: 'redis-server --requirepass ${PRD_REDIS_PASS}'
    volumes:
      - redis-prd:/data
    ports:
      - "6379:6379"