version: '3.0'

networks:
  monitoring:

services:
  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire
    restart: always
    expose:
      - 18888
    ports:
      - "4317:18889"
    networks:
      - monitoring