volumes:
  azure-storage-emulator:

services:
  azure-storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azure-storage-emulator
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
