version: '3.0'

volumes:
  azure-storage-emulator:
  tabby:

services:
  azure-storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azure-storage-emulator
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  tabby:
    container_name: tabby
    restart: always
    image: tabbyml/tabby
    entrypoint: /opt/tabby/bin/tabby-cpu
    command: serve --model StarCoder-1B
    volumes:
      - tabby:/data
    ports:
      - "8090:8080"
