name: jellyfin

networks:
  general:
    external: true

volumes:
  jellyfin-cfg:
  jellyfin-cache:

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    group_add:
      - 991
    restart: always
    environment:
      - JELLYFIN_PublishedServerUrl=https://192.168.3.254
    ports:
      - "7359:7359/udp"
      - "8096:8096/tcp"
    volumes:
      - jellyfin-cfg:/config
      - jellyfin-cache:/cache
      - /mnt/downloads:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - general
