name: jellyfin

networks:
  general:
    external: true

volumes:
  jellyfin-cfg:
  jellyfin-cache:
  radarr-cfg:
  sonarr-cfg:

services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - radarr-cfg:/config
      - /mnt/data:/data
    networks:
      - general
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - sonarr-cfg:/config
      - /mnt/data:/data
    networks:
      - general
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    group_add:
      - 991
    restart: always
    environment:
      - JELLYFIN_PublishedServerUrl=https://192.168.3.254
      - TZ=Europe/Kyiv
    ports:
      - "7359:7359/udp"
      - "8096:8096/tcp"
    volumes:
      - jellyfin-cfg:/config
      - jellyfin-cache:/cache
      - /mnt/data/media:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - general
