version: '3.8'

networks:
  media:

volumes:
  downloads:
  qbittorrent:
  jellyfin-cfg:
  jellyfin-cache:
  
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent:/config
      - downloads:/downloads
    expose:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - jellyfin-cfg:/config
      - jellyfin-cache:/cache
      - downloads:/media
    restart: always
    ports:
      - "1900:1900/udp"
      - "7359:7359/udp"
      - "8920:8920/tcp"
      - "8096:8096/tcp"
    environment:
      - JELLYFIN_PublishedServerUrl=https://192.168.3.254
    networks:
      - media
