version: '3.8'

networks:
  media:

volumes:
  downloads:
  qbittorrent:
  jellyfin-cfg:
  jellyfin-cache:
  media-file-browser:

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent:/config
      - downloads:/downloads
    expose:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media
  jellyfin:
    image: jellyfin/jellyfin:10.8.13
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - "109"
      - "44"
      - "106"
    volumes:
      - jellyfin-cfg:/config
      - jellyfin-cache:/cache
      - downloads:/media
    restart: always
    ports:
      - "1900:1900/udp"
      - "7359:7359/udp"
      - "8920:8920/tcp"
      - "8096:8096/tcp"
    environment:
      - JELLYFIN_PublishedServerUrl=https://192.168.3.254
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - media
  downloads-file-browser:
    container_name: downloads-file-browser
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    expose:
      - "8080"
    volumes:
      - downloads:/data
      - media-file-browser:/config
    environment:
      - FB_BASEURL=/
      - FB_NOAUTH=true
    restart: always
    networks:
      - media
