name: nginx

networks:
  general:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ${CFG_PATH}:/etc/nginx
      - ${CERTS_PATH}/_wildcard.server.local.pem:/etc/nginx/cert.pem:ro
      - ${CERTS_PATH}/_wildcard.server.local-key.pem:/etc/nginx/key.pem:ro
    networks:
      - general