networks:
  general_general:
    external: true
  monitoring_monitoring:
    external: true
  media_media:
    external: true
  aspire_monitoring:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ${CFG_PATH}:/etc/nginx/nginx.conf:ro
      - ${CERTS_PATH}/_wildcard.server.home.pem:/etc/nginx/cert.pem:ro
      - ${CERTS_PATH}/_wildcard.server.home-key.pem:/etc/nginx/key.pem:ro
    networks:
      - general_general
      - media_media
      - monitoring_monitoring
      - aspire_monitoring