services:
  remove-sound-tg-bot-converter-dev:
    image: infinitu1327/ffmpeg-worker:az-nightly
    container_name: remove-sound-tg-bot-converter-dev
    restart: always
    environment:
      Storage:ConnectionString: ${STORAGE_CONNECTION}
      Storage:Input:Queue: converter-input
      Storage:Input:Container: converter-input
      Storage:Output:Queue: converter-output
      Storage:Output:Container: converter-output
      FFMpeg:Path: /usr/bin/ffmpeg
      FFMpeg:Arguments: -max_muxing_queue_size 1024 -c copy -an -y
      Delay: 00:01:00
      OTEL_SERVICE_NAME: remove-sound-tg-bot-converter-dev
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS}
  remove-sound-tg-bot-thumbnailer-dev:
    container_name: remove-sound-tg-bot-thumbnailer-dev
    image: infinitu1327/ffmpeg-worker:az-nightly
    restart: always
    environment:
      Storage:ConnectionString: ${STORAGE_CONNECTION}
      Storage:Input:Queue: thumbnailer-input
      Storage:Input:Container: thumbnailer-input
      Storage:Output:Queue: thumbnailer-output
      Storage:Output:Container: thumbnailer-output
      FFMpeg:Path: /usr/bin/ffmpeg
      FFMpeg:Arguments: -map 0:v:0 -ss 1 -vframes 1 -y
      TargetExtension: .jpg
      Delay: 00:01:00
      OTEL_SERVICE_NAME: remove-sound-tg-bot-thumbnailer-dev
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS}
