services:
  remove-sound-tg-bot-converter-prd:
    image: infinitu1327/ffmpeg-worker:az-stable
    container_name: remove-sound-tg-bot-converter-prd
    restart: always
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APP_INSIGHTS_CONNECTION}
      Storage:ConnectionString: ${STORAGE_CONNECTION}
      Storage:Input:Queue: converter-input
      Storage:Input:Container: converter-input
      Storage:Output:Queue: converter-output
      Storage:Output:Container: converter-output
      FFMpeg:Path: /usr/bin/ffmpeg
      FFMpeg:Arguments: -max_muxing_queue_size 1024 -c copy -an -y
      Delay: 00:01:00
      Name: remove-sound-tg-bot-converter-prd
  remove-sound-tg-bot-thumbnailer-prd:
    container_name: remove-sound-tg-bot-thumbnailer-prd
    image: infinitu1327/ffmpeg-worker:az-stable
    restart: always
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APP_INSIGHTS_CONNECTION}
      Storage:ConnectionString: ${STORAGE_CONNECTION}
      Storage:Input:Queue: thumbnailer-input
      Storage:Input:Container: thumbnailer-input
      Storage:Output:Queue: thumbnailer-output
      Storage:Output:Container: thumbnailer-output
      FFMpeg:Path: /usr/bin/ffmpeg
      FFMpeg:Arguments: -map 0:v:0 -ss 1 -vframes 1 -y
      FFMpeg:TargetExtension: .jpg
      Delay: 00:01:00
      Name: remove-sound-tg-bot-thumbnailer-prd
