extensions:
  bearertokenauth/server:
    filename: "bearer.token"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: bearertokenauth/server

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:
    verbosity: detailed

processors:
  batch:
    timeout: 10s

service:
  extensions:
    - bearertokenauth/server
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/jaeger ]

    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]

    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]