server {
    listen 443 ssl;

    ssl_certificate cert.pem;
    ssl_certificate_key key.pem;
    server_name torrent.server.home;

    location / {
        proxy_pass http://qbittorrent:8080;

        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
